# Generated by Django 3.0.4 on 2020-05-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V2rayConfig',
            fields=[
                ('UUID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Path', models.CharField(max_length=255)),
                ('Log', models.CharField(max_length=255)),
                ('Level', models.CharField(max_length=10)),
                ('Port', models.CharField(max_length=15)),
                ('Protocol', models.CharField(max_length=15)),
                ('DataProtocol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='V2rayShadowsocks',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=18)),
            ],
        ),
    ]
