# Generated by Django 3.0.4 on 2020-05-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V2rayPath',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.CharField(max_length=255)),
            ],
        ),
    ]
