# Generated by Django 3.0.4 on 2020-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2rayConfig',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.CharField(max_length=255)),
                ('Log', models.CharField(max_length=255)),
                ('Level', models.CharField(max_length=10)),
                ('Port', models.IntegerField()),
                ('Portocol', models.CharField(max_length=15)),
                ('UUID', models.CharField(max_length=255)),
                ('DataPortocol', models.CharField(max_length=15)),
            ],
        ),
    ]
