# Generated by Django 3.0.4 on 2020-05-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_v2rayconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V2rayPath',
        ),
    ]
