# Generated by Django 3.0.4 on 2020-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_v2raypath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v2rayconfig',
            name='ID',
        ),
        migrations.AlterField(
            model_name='v2rayconfig',
            name='UUID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
