# Generated by Django 3.0.4 on 2020-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200519_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v2rayconfig',
            name='Port',
            field=models.CharField(max_length=15),
        ),
    ]
