# Generated by Django 3.0.4 on 2020-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200519_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2rayShadowsocks',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=18)),
            ],
        ),
    ]
