# Generated by Django 3.0.4 on 2020-05-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_v2rayshadowsocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v2rayconfig',
            old_name='DataPortocol',
            new_name='DataProtocol',
        ),
        migrations.RenameField(
            model_name='v2rayconfig',
            old_name='Portocol',
            new_name='Protocol',
        ),
    ]
